libp2p/js-libp2p-websockets

- src/index.js
- tests/libp2p-websockets-test.js
Also renamed `ready` to `connect` on `.dial` method.
> Add echo tests

- src/index.js
- tests/libp2p-websockets-test.js
Oops, just noticed I should have not renamed the `ready` callback on #2, so this reverts it.
> Rename callback to ready again

- README.md
- gulpfile.js
- package.json
- src/index.js
- src/listener.js
- test/browser.js
- test/compliance.node.js
- test/node.js
Investigate `delay`. Ref https://github.com/pull-stream/pull-ws/issues/13
> [WIP] Move to pull-streams

- .gitignore
- .travis.yml
- README.md
- package.json
- src/listener.js
Fixes #31 
Ref https://github.com/ipfs/js-ipfs/pull/485
> feat: upgrade to aegir@9

- package.json
- src/index.js
If the callback was passed to dial, we would get a funny error
> fix: onConnect does not follow callback pattern

- .gitignore
- package.json
- src/index.js
- src/listener.js
I started looking at ipfs/js-ipfs#632, and traced those deprecation warnings largely to this repo.  The lodash.contains dependency is easy to fix.  The others are all coming from the most recent `gulp` module, so will have to be addressed there.
> Use lodash.includes instead of the deprecated lodash.contains

- .gitignore
- circle.yml
- package.json
- src/listener.js
- test/node.js
> feat: resolve 0 addresses

- .travis.yml
- README.md
- package.json
- test/node.js
In the context of [libp2p/libp2p#74](https://github.com/libp2p/libp2p/issues/74), the badge for [discuss.libp2p.io](http://discuss.libp2p.io) was added.
Dependencies were also updated and Travis CI added and `ipv6` tests were skipped [libp2p/js-libp2p-websockets#84](https://github.com/libp2p/js-libp2p-websockets/issues/84)
> chore: add discourse badge

- package.json
This PR adds support for implicit HTTP multiaddrs added in https://github.com/multiformats/js-multiaddr-to-uri/pull/7
cc @alanshaw  https://github.com/ipfs/js-ipfs/pull/2377
> chore: update multiaddr-to-uri

- package.json
- src/index.js
- src/listener.js
- test/node.js
This adds multiaddr 7 support to filtering. multiaddr 7 uses p2p instead of ipfs. Since we currently decapsulate with 'ipfs' this causes valid addresses to get filtered out. Filter will now check for decapsulateCode on the multiaddr and use that if it exists, otherwise it defaults to its previous behavior.
> fix: support multiaddr 7

- .gitignore
- .travis.yml
- test/node.js
The ephemeral port and host skips are no longer valid, so tests have been added for those.
The other skipped test is now covered by the interface tests, so it's no longer needed.
> test: fix skips

- src/listener.js
This catches errors that may occur when attempting to upgrade inbound connections. Any failures will result in the error being logged and the MultiaddrConnection being closed.
> fix: catch inbound upgrade errors

- package.json
- src/socket-to-conn.js
- test/node.js
several it-* modules leverage bufferlist, but ws does not. We need to convert buffer lists to buffers before handing the data off to ws for transmission
libp2p-tcp does this, https://github.com/libp2p/js-libp2p-tcp/blob/master/src/socket-to-conn.js#L22-L27
> fix: support bufferlist usage

- package.json
- src/socket-to-conn.js
- test/compliance.node.js
This module was still using `interface-transport`. Updated to use `libp2p-interfaces` instead.
> chore: use libp2p-interfaces

- src/listener.js
When upgrading sockets to MultiaddConnections, it's possible for an error to be thrown.
This can crash the application if a client disconnects prior to the listener
uprading the socket. Errors will now be caught and logged
when attempting to upgrade the socket.
Per comment on [libp2p/js-libp2p-websockets#106#pullrequestreview-364926334](https://github.com/libp2p/js-libp2p-websockets/pull/106#pullrequestreview-364926334)
> fix: catch thrown maConn errors in listener

- package.json
- src/socket-to-conn.js
libp2p tests pass with this PR 🎉
> fix: add buffer

- package.json
- src/socket-to-conn.js
- test/browser.js
- test/node.js
Depends on:
BREAKING CHANGES:
- All deps used by this module now use Uint8Arrays in place of Buffers
> fix: replace node buffers with uint8arrays

- package.json
to remove `web-encoding` from the dep tree per https://github.com/multiformats/js-multiaddr-to-uri/pull/66
> chore: update multiaddr to uri

- src/listener.js
- test/node.js
Related to the flagged issue in https://github.com/libp2p/js-libp2p/pull/930
Shortly, when libp2p calls `libp2p.transportManager.getAddrs()`, the underlying websockets transport would return a `ws` multiaddr when listening on a `wss` multiaddr and this address was being incorrectly advertised
> fix: listener get addrs with wss

- .aegir.cjs
- test/browser.ts
- test/node.ts
Update to the lastest libp2p interfaces
> fix: update interfaces

- .aegir.js
- package.json
The extra config wasn't necessary, upgrades aegir to run the tests in a way that respects the browser override field in package.json.
> fix: remove entrypoint config

- package.json
- src/index.ts
constructor.name only really works in node.
> fix: update interfaces and use static string for toStringTag

- src/index.ts
- I've noticed an issue when including this package in another typescript project. The `index.d.ts` file created during the build process would include an in-line import in the `dial` function declaration of `Promise<import("@libp2p/interface-connection/dist/src").Connection>;`
- This would result in the following build error in my project:
`../../node_modules/@libp2p/websockets/dist/src/index.d.ts(19,104): error TS2694: Namespace '"@libp2p/interface-connection/dist/src"' has no exported member 'Connection'.`
- By declaring the `Connection` import explicitly, we avoid the strange in-line import of a `dist/src` location and I am able to build my project correctly.
I believe it is possible that this issue: https://github.com/libp2p/js-libp2p-websockets/issues/163 is also the result of the …
> fix: update dial function return type to avoid Connection import issue

- src/socket-to-conn.ts
I simulated that it's not working by attaching a socket to a conn object that I can manually close. Not sure how to trigger the close socket event without hacking (or without calling close on conn)
resolves #179
> fix: socket close event not working in browser

- .aegir.js
- README.md
- package.json
- src/index.ts
- test/browser.ts
- test/compliance.node.ts
- test/node.ts
`@libp2p/components` is a choke-point for our dependency graph as it depends on every interface, meaning when one interface revs a major `@libp2p/components` major has to change too which means every module depending on it also needs a major.
Switch instead to constructor injection of simple objects that let modules declare their dependencies on interfaces directly instead of indirectly via `@libp2p/components`
Refs https://github.com/libp2p/js-libp2p-components/issues/6
BREAKING CHANGE: modules no longer implement `Initializable` instead switching to constructor injection
> fix!: remove @libp2p/components

- src/filters.ts
- src/index.ts
- test/browser.ts
Browsers can dial IP addresses just fine. There's no need for this to be only DNS addresses.
> fix: Only filter by wss not dns

- package.json
While following the example of how to do a basic libp2p setup, if we only configure webSockets as our [transport](https://github.com/libp2p/js-libp2p/blob/master/doc/GETTING_STARTED.md#transports) the types will be undefined.
```bash
node_modules/@libp2p/websockets/dist/src/index.d.ts:5:36 - error TS7016: Could not find a declaration file for module 'ws'. '/Users/horizon/Desktop/test/node_modules/ws/index.js' implicitly has an 'any' type.
Try `npm i --save-dev @types/ws` if it exists or add a new declaration (.d.ts) file containing `declare module 'ws';`
5 import type { ClientOptions } from 'ws';
~~~~
```
Perhaps these types should be exported in a better way? Especially since they are required in [it-ws](https://www.npmjs.com/package/it-ws) but if so then maybe the are not properly …
> deps: add ws types to main dependencies
